### PR TITLE
Feature/fetch package containing bot descriptors

### PR DESCRIPTION
**Pull request by ginccc**
Solving two issues:
* Which bots are using a specific package?
* Which packages are using a specific dictionary or rules or output?

added POST endpoints to retrieve bot and package descriptors if they contain a specific resource
-> resource uri as body
e.g. 
```
curl -X POST --header 'Content-Type: text/plain' --header 'Accept: application/json' -d 'eddi://ai.labs.package/packagestore/packages/<ID>?version=<VERSION>' 'http://localhost:7070/botstore/bots/descriptors'
```

```
curl -X POST --header 'Content-Type: text/plain' --header 'Accept: application/json' -d 'eddi://ai.labs.regulardictionary/regulardictionarystore/regulardictionaries/<ID>?version=<VERSION>' 'http://localhost:7070/packagestore/packages/descriptors'
```

---
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/103)

### CODE REVIEW

**Comment by ginccc** [comment]
*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/bots/mongo/BotStore.java, line 80 at r1](https://reviewable.io/reviews/labsai/eddi/103#-LBMZJRtDJe7SbxC9kvI:-LBMcXplAvBrhoSD8Jj2:b-8c6eo4) ([raw file](https://github.com/labsai/eddi/blob/5e2eef265b15ff567ce47850054c1dbd9f7621ac/configurationrepository-impl/src/main/java/ai/labs/resources/impl/bots/mongo/BotStore.java#L80)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

Can you do this with `map`?
</blockquote></details>

documentDescriptorStore throws an exception. this exception will be delegated up all the way to the rest api endpoint, in which it is then interpreted as httpcode an message 

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103)*

**Comment by ginccc** [comment]
*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/bots/mongo/BotStore.java, line 80 at r1](https://reviewable.io/reviews/labsai/eddi/103#-LBMZJRtDJe7SbxC9kvI:-LBMcnct6qFbgIEo4Pj4:bz8x3wy) ([raw file](https://github.com/labsai/eddi/blob/5e2eef265b15ff567ce47850054c1dbd9f7621ac/configurationrepository-impl/src/main/java/ai/labs/resources/impl/bots/mongo/BotStore.java#L80)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

documentDescriptorStore throws an exception. this exception will be delegated up all the way to the rest api endpoint, in which it is then interpreted as httpcode an message 
</blockquote></details>

would need to make a try-catch with map, and that would have broken this mechanism

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103)*

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103#-:-LBN30u3ABb7LJ0asTaG:bnfp4nl)*

**Comment by AlmaasAre** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[configurationrepository-definition/src/main/java/ai/labs/resources/rest/bots/IRestBotStore.java, line 37 at r1](https://reviewable.io/reviews/labsai/eddi/103#-LBUh25l0z28rWFXQHgv:-LBUh25l0z28rWFXQHgw:bkvkle6) ([raw file](https://github.com/labsai/eddi/blob/5e2eef265b15ff567ce47850054c1dbd9f7621ac/configurationrepository-definition/src/main/java/ai/labs/resources/rest/bots/IRestBotStore.java#L37)):*
> ```Java
>             @QueryParam("filter") @DefaultValue("") String filter,
>             @QueryParam("index") @DefaultValue("0") Integer index,
>             @QueryParam("limit") @DefaultValue("20") Integer limit,
> ```

should probably have an upper limit? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103)*

**Comment by AlmaasAre** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/bots/rest/RestBotStore.java, line 55 at r1](https://reviewable.io/reviews/labsai/eddi/103#-LBUhJR_0IgoovRv2BGd:-LBUhJR_0IgoovRv2BGe:bi8r9zo) ([raw file](https://github.com/labsai/eddi/blob/5e2eef265b15ff567ce47850054c1dbd9f7621ac/configurationrepository-impl/src/main/java/ai/labs/resources/impl/bots/rest/RestBotStore.java#L55)):*
> ```
> createMaleFormattedResourceUriException
> ```


createMalFormattedResourceUriException*

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103)*

**Comment by AlmaasAre** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/packages/mongo/PackageStore.java, line 94 at r1](https://reviewable.io/reviews/labsai/eddi/103#-LBUh_zX9Rfjy8bynMTv:-LBUh_zX9Rfjy8bynMTw:b-qi43s) ([raw file](https://github.com/labsai/eddi/blob/5e2eef265b15ff567ce47850054c1dbd9f7621ac/configurationrepository-impl/src/main/java/ai/labs/resources/impl/packages/mongo/PackageStore.java#L94)):*
> ```Java
> 
>         List<IResourceId> getPackageDescriptorsContainingResource(URI resourceURI) throws ResourceNotFoundException {
>             String searchQuery = String.format("JSON.stringify(this).indexOf('%s')!=-1", resourceURI);
> ```

seems prone to injection no?

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103)*

**Comment by AlmaasAre** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/packages/rest/RestPackageStore.java, line 44 at r1](https://reviewable.io/reviews/labsai/eddi/103#-LBUhiLo0OzN6c_ko2rb:-LBUhiLo0OzN6c_ko2rc:b-h5pz9q) ([raw file](https://github.com/labsai/eddi/blob/5e2eef265b15ff567ce47850054c1dbd9f7621ac/configurationrepository-impl/src/main/java/ai/labs/resources/impl/packages/rest/RestPackageStore.java#L44)):*
> ```Java
>     @Override
>     public List<DocumentDescriptor> readPackageDescriptors(String filter, Integer index, Integer limit, String containingResourceUri) {
>         if (containingResourceUri.startsWith("eddi://")) {
> ```

should maybe be a helper function? Seems a bit fragile to me. isValidURI(containingResourceUri) or something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103)*

**Comment by AlmaasAre** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/103#-:-LBUi2U2CgrXApQviZfK:bnfp4nl)*

**Pull request merged**
