### PR TITLE
Feature/http2

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/76)

### CODE REVIEW

**Comment by rolandpickl** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[apiserver/config/development/webServer.properties, line 4 at r2](https://reviewable.io:443/reviews/labsai/eddi/76#-KsjT1toXA3QUNsLid8-:-KsjT1toXA3QUNsLid80:b-qh4vkx) ([raw file](https://github.com/labsai/eddi/blob/82c883152f7a8b3d372dcdb7d60a06e00c1860b4/apiserver/config/development/webServer.properties#L4)):*
> ```INI
> webServer.httpPort=7070
> webServer.httpsPort=7443
> webServer.keyStorePath=keystore/eddi_selfsigned.jks
> ```

selfsigned jks is not enough. This needs to be injected from an outside the docker container, otherwise it cannot be used with standard implementations like facebook or skype

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/76)*

**Comment by rolandpickl** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/76)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[automatedtesting-impl/src/main/java/ai/labs/testing/impl/TestCaseRuntime.java, line 89 at r2](https://reviewable.io:443/reviews/labsai/eddi/76#-Kslekt2N3r8F1jfh207:-Kslekt2N3r8F1jfh208:bdgo6m7) ([raw file](https://github.com/labsai/eddi/blob/82c883152f7a8b3d372dcdb7d60a06e00c1860b4/automatedtesting-impl/src/main/java/ai/labs/testing/impl/TestCaseRuntime.java#L89)):*
> ```Java
>             //wait until deployment has finished
>             if (!Objects.equals(restBotAdministration.getDeploymentStatus(Deployment.Environment.test, botId, botVersion), Deployment.Status.IN_PROGRESS.toString())) {
>                 break;
> ```

What if it will never happen? You need some limit with error logging. 
Also, I don't like this solution at all. Is there some sort of Promises or Features? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/76)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[automatedtesting-impl/src/main/java/ai/labs/testing/impl/TestCaseRuntime.java, line 73 at r2](https://reviewable.io:443/reviews/labsai/eddi/76#-KslfK6oumL95dZ_kh9a:-KslfK6pyVSp4r7JsRkI:bd9nw31) ([raw file](https://github.com/labsai/eddi/blob/82c883152f7a8b3d372dcdb7d60a06e00c1860b4/automatedtesting-impl/src/main/java/ai/labs/testing/impl/TestCaseRuntime.java#L73)):*
> ```Java
>         do {
>             deploymentStatus = restBotAdministration.getDeploymentStatus(Deployment.Environment.test, botId, botVersion);
>             if (Objects.equals(deploymentStatus, Deployment.Status.IN_PROGRESS.toString())) {
> ```

What if it will never happen? You need some limit with error logging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/76)*

**Pull request merged**
