### PR TITLE
Facebook implementation bugfix

### PR DESCRIPTION
**Pull request by rolandpickl**
The facebook implementation is ready for just text-in and text out. Please review. Next step is the implementation of quick replies.

---
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/72)

### CODE REVIEW

**Comment by ginccc** [comment]
*[conversationmemory-definition/src/main/java/ai/labs/memory/model/ConversationMemorySnapshot.java, line 14 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNWjYhBs1Qpn1X84YK:-KsNWjYiBhrFKXMhicQG:b1v2w2b) ([raw file](https://github.com/labsai/eddi/blob/849557974222ec15aa721ad96cc5134720b3c860/conversationmemory-definition/src/main/java/ai/labs/memory/model/ConversationMemorySnapshot.java#L14)):*
> ```Java
>  * @author ginccc
>  */
> @Getter
> ```

why did you remove the lombok annotations and make the getter/setter manually?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[conversationmemory-impl/src/main/java/ai/labs/memory/ConversationMemoryUtilities.java, line 118 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNWxvee8zCaLYYH2TI:-KsNWxvee8zCaLYYH2TJ:brjl69l) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/conversationmemory-impl/src/main/java/ai/labs/memory/ConversationMemoryUtilities.java#L118)):*
> ```Java
>                     if (returnDetailed || resultSnapshot.isPublic()) {
>                         Object result = resultSnapshot.getResult();
>                         simpleConversationStep.getData().add(
> ```

"Data" is old, "ConversationStep" is new. Any reasons for changing it back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[corerest-definition/pom.xml, line 19 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNXD9WyuzLi6FlEugT:-KsNXD9Xinblsg6pGy5P:b-u956nn) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/corerest-definition/pom.xml#L19)):*
> ```XML
>         <dependency>
>             <groupId>org.jboss.resteasy</groupId>
>             <artifactId>resteasy-jaxrs</artifactId>
> ```

this has been moved to the root pom file, no need to reference it here anymore. I think you have an not updated branch. merge it first pls!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[corerest-definition/src/main/java/ai/labs/rest/restinterfaces/RestInterfaceFactory.java, line 66 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNXZ0guVBOIli0fQVK:-KsNXZ0guVBOIli0fQVL:bdqwjsp) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/corerest-definition/src/main/java/ai/labs/rest/restinterfaces/RestInterfaceFactory.java#L66)):*
> ```Java
>         ResteasyClient client = clients.get(targetServerUri);
>         if(client == null) {
>             //CloseableHttpClient httpClient = targetServerUri.startsWith("https") ?
> ```

delete the comments if not needed anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[coreserver/src/main/java/ai/labs/core/rest/internal/RestBotEngine.java, line 76 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNXe4TEhkE5KEiHMyJ:-KsNXe4TEhkE5KEiHMyK:b-kk9tz9) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/coreserver/src/main/java/ai/labs/core/rest/internal/RestBotEngine.java#L76)):*
> ```Java
>             IConversation conversation = latestBot.startConversation(null);
>             String conversationId = storeConversationMemory(conversation.getConversationMemory(), environment);
>             log.info("conversationid:{}", conversationId);
> ```

log.debug ?! otherwise pls remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[coreserver/src/main/java/ai/labs/core/rest/internal/RestBotEngine.java, line 116 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNXxNP02xEGxSFRFbl:-KsNXxNQDEffW-yGAhfs:b-121ahn) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/coreserver/src/main/java/ai/labs/core/rest/internal/RestBotEngine.java#L116)):*
> ```Java
> 
>     @Override
>     public String readConversation(Deployment.Environment environment, String botId, String conversationId) {
> ```

there is a readConversation already, why not using this, and iterating the results in an utility method in ConversationMemoryUtilities for instance..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[coreserver/src/main/java/ai/labs/core/rest/internal/RestBotEngine.java, line 131 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNYWfqEB7X-StUQxOO:-KsNYWfqEB7X-StUQxOP:b7ej3ul) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/coreserver/src/main/java/ai/labs/core/rest/internal/RestBotEngine.java#L131)):*
> ```Java
>                 for (ConversationMemorySnapshot.PackageRunSnapshot packageRunSnapshot : conversationStep.getPackages()) {
>                     for (ConversationMemorySnapshot.ResultSnapshot resultSnapshot : packageRunSnapshot.getLifecycleTasks()) {
>                         if (resultSnapshot.getKey().equals("output:final")) {
> ```

this is also old. new version has various outputs such as output:text:action1 output:text:action2 or output:image:action1 and so on... pls update your branch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 181 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNZCmiAu7ywUp9bgNN:-KsNZCmjZCOZyVXp1FqB:b-svfo8x) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L181)):*
> ```Java
>                 messengerClientCache.get(botId).getSendClient().sendSenderAction(senderId, SenderAction.TYPING_OFF);
>             } catch (MessengerApiException e) {
>                 e.printStackTrace();
> ```

either throw it or log it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by ginccc** [comment]
*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 206 at r1](https://reviewable.io:443/reviews/labsai/eddi/72#-KsNZWwLh0IMV9DPrF26:-KsNZWwLh0IMV9DPrF27:btz3vse) ([raw file](https://github.com/labsai/eddi/blob/540b3db2a459f5e8f00ad38dac17880db76f56d3/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L206)):*
> ```Java
>     private String getOutputText(String json) {
> 
>         String output = "I don't understand, please rephrase your question";
> ```

this should be solved with behavior rules instead, such as that there is a default rule that applies if no other rules applies (e.g. last rule in a group, or rule that catches "unknown(*)" expressions)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/72)*

**Comment by rolandpickl** [comment]
pull was done from wrong branch. closing pull request and redoing changes

**Pull request closed without merging**
