### PR TITLE
added permanent deletion query param for conversations

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/107)

### CODE REVIEW

**Comment by sondremare** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/monitor/rest/RestConversationStore.java, line 144 at r1](https://reviewable.io/reviews/labsai/eddi/107#-LBtdoal8dxzkzTU7lKB:-LBtdoal8dxzkzTU7lKC:brpmoq0) ([raw file](https://github.com/labsai/eddi/blob/769d1f85e36c7430e14d32d1452ea98dea06e4fb/configurationrepository-impl/src/main/java/ai/labs/resources/impl/monitor/rest/RestConversationStore.java#L144)):*
> ```Java
>             log.info(String.format("Conversation has been permanently deleted (id=%s)", conversationId));
>         }
>         //else {
> ```

remove ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/107)*

**Comment by sondremare** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/monitor/rest/RestConversationStore.java, line 139 at r1](https://reviewable.io/reviews/labsai/eddi/107#-LBtox3W-m9xt1MN78MI:-LBtox3W-m9xt1MN78MJ:buh37s2) ([raw file](https://github.com/labsai/eddi/blob/769d1f85e36c7430e14d32d1452ea98dea06e4fb/configurationrepository-impl/src/main/java/ai/labs/resources/impl/monitor/rest/RestConversationStore.java#L139)):*
> ```Java
>             throws IResourceStore.ResourceStoreException, IResourceStore.ResourceNotFoundException {
>         RuntimeUtilities.checkNotNull(conversationId, "conversationId");
> ```

my suggestion is to just move the comment up to here. Remove the else part of it.

---

*[configurationrepository-impl/src/main/java/ai/labs/resources/impl/monitor/rest/RestConversationStore.java, line 145 at r1](https://reviewable.io/reviews/labsai/eddi/107#-LBtouAW2-0T_-1O__4c:-LBtouAW2-0T_-1O__4d:b-a2cogi) ([raw file](https://github.com/labsai/eddi/blob/769d1f85e36c7430e14d32d1452ea98dea06e4fb/configurationrepository-impl/src/main/java/ai/labs/resources/impl/monitor/rest/RestConversationStore.java#L145)):*
> ```
> DocumentDescriptorInterceptor
> ```

---


*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/107)*

**Comment by sondremare** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/107#-:-LBtrKCLEiyXB7Frhpoe:bnfp4nl)*

**Comment by AlmaasAre** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/labsai/eddi/107#-:-LBtsx1vCsMrxKh_d3Pn:bnfp4nl)*

**Pull request merged**
