### PR TITLE
Feature/property extraction

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/84)

### CODE REVIEW

**Comment by AlmaasAre** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[propertydisposer-impl/src/main/java/ai/labs/property/impl/PropertyDisposerTask.java, line 22 at r2](https://reviewable.io:443/reviews/labsai/eddi/84#-KxhcJXfD9vPyywh0aGJ:-KxhcJXfD9vPyywh0aGK:b-ga7qj9) ([raw file](https://github.com/labsai/eddi/blob/010cbd6e9347ed8f80803795ce7799cc13fc2e67/propertydisposer-impl/src/main/java/ai/labs/property/impl/PropertyDisposerTask.java#L22)):*
> ```Java
>     private static final String ACTIONS_IDENTIFIER = "actions";
>     private static final String CATCH_ANY_INPUT_AS_PROPERTY_ACTION = "CATCH_ANY_INPUT_AS_PROPERTY";
>     private static final String INPUT_INITIAL_IDENTIFIER = "input:initial";
> ```

are we using these strings anywhere else? Gather all the strings into one file maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/84)*

**Comment by AlmaasAre** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/84#-:-Kxhcndta4d70x05HHJr:bnfp4nl)*

**Comment by ginccc** [comment]
*[propertydisposer-impl/src/main/java/ai/labs/property/impl/PropertyDisposerTask.java, line 22 at r2](https://reviewable.io:443/reviews/labsai/eddi/84#-KxhcJXfD9vPyywh0aGJ:-Kxhd_yd-8boOHt6NGui:b-302tby) ([raw file](https://github.com/labsai/eddi/blob/010cbd6e9347ed8f80803795ce7799cc13fc2e67/propertydisposer-impl/src/main/java/ai/labs/property/impl/PropertyDisposerTask.java#L22)):*
<details><summary><i>Previously, AlmaasAre (Are Almaas) wrote…</i></summary><blockquote>

are we using these strings anywhere else? Gather all the strings into one file maybe?
</blockquote></details>

Well, not really. They might be used once else where. But the thing is, these strings are plugin related and thus dynamically depending on whether they are defined in the config or not. 
Would break a bit the paradigm of summing them up somewhere. 
Maybe each plugin should over all identifiers to a sort of registry so that other plugins could pick them up... not sure .. :-/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/84)*

**Comment by AlmaasAre** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[propertydisposer-impl/src/main/java/ai/labs/property/impl/PropertyDisposerTask.java, line 22 at r2](https://reviewable.io:443/reviews/labsai/eddi/84#-KxhcJXfD9vPyywh0aGJ:-KxheMs7yUfmxDX-I9r0:b-tk8irl) ([raw file](https://github.com/labsai/eddi/blob/010cbd6e9347ed8f80803795ce7799cc13fc2e67/propertydisposer-impl/src/main/java/ai/labs/property/impl/PropertyDisposerTask.java#L22)):*
>Maybe each plugin should over all identifiers to a sort of registry so that other plugins could pick them up... not sure .. :-/

Meh, think it's good enough for now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/84)*

**Comment by forjes14** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/84#-:-Kxhg6G6SInGXZPzDpvs:bnfp4nl)*

**Pull request merged**
