### PR TITLE
Improvement/start script with env varibles

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/46)

### CODE REVIEW

**Comment by AlmaasAre** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Dockerfile, line 21 at r2](https://reviewable.io:443/reviews/labsai/eddi/46#-KptBoQF1mbCyuXsXaBV:-KptBoQF1mbCyuXsXaBW:b9dkqjt) ([raw file](https://github.com/labsai/eddi/blob/3254cd2244440c2186bd4122fe76741b6318c719/Dockerfile#L21)):*
> ```Dockerfile
> #COPY not ADD the artifact (the current eddi structure is assumed)
> COPY /apiserver/target/apiserver-$EDDI_VERSION-package.zip /apiserver/install
> COPY /start_eddi.sh /apiserver
> ```

name it configure_environment.sh maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/46)*

**Comment by ginccc** [comment]
*[Dockerfile, line 21 at r2](https://reviewable.io:443/reviews/labsai/eddi/46#-KptBoQF1mbCyuXsXaBV:-KptCQ2w-AXXGbVp8zwV:budj3rz) ([raw file](https://github.com/labsai/eddi/blob/3254cd2244440c2186bd4122fe76741b6318c719/Dockerfile#L21)):*
<details><summary><i>Previously, AlmaasAre (Are Almaas) wrote…</i></summary><blockquote>

name it configure_environment.sh maybe?
</blockquote></details>

well, the way it is now it also starts eddi. so maybe start_eddi_with_environment_vars.sh ?!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/46)*

**Comment by AlmaasAre** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Dockerfile, line 21 at r2](https://reviewable.io:443/reviews/labsai/eddi/46#-KptBoQF1mbCyuXsXaBV:-KptCeJARBrJl1cpxsHI:b-tfrgh4) ([raw file](https://github.com/labsai/eddi/blob/3254cd2244440c2186bd4122fe76741b6318c719/Dockerfile#L21)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

well, the way it is now it also starts eddi. so maybe start_eddi_with_environment_vars.sh ?!
</blockquote></details>

oh right. sure just leave it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/46)*

**Comment by AlmaasAre** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/46#-:-KptCkX6Ai1eKpGsY66H:bnfp4nl)*

**Comment by sondremare** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/46#-:-KptGSin0SQrH4XK6eZl:bnfp4nl)*

**Pull request merged**
