### PR TITLE
Feature/export import bots

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/89)

### CODE REVIEW

**Comment by kennethlynne** [comment]
No documentation that should change as a consequence of this?

Would also prefer a small note in the PR description so it is clearer how it works for the end user (developer)

---

Reviewed 4 of 11 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/CallbackMatcher.java, line 21 at r3](https://reviewable.io:443/reviews/labsai/eddi/89#-KzPVr38lClJ66p3UNeO:-KzPVr38lClJ66p3UNeP:b-fgzqqu) ([raw file](https://github.com/labsai/eddi/blob/3e43e2f40c404fb8dfbf268ca02d195230c17512/backupservice-impl/src/main/java/ai/labs/backupservice/impl/CallbackMatcher.java#L21)):*
> ```Java
>     }
> 
>     public String replaceMatches(CharSequence charSequence, Callback callback) throws CallbackMatcherException {
> ```

this should be easy to unit test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/89#-:-KzPW2cItEYLk8ZVvdb3:b-45qfid)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/89#-:-KzPWZmYitHCfixaIVo-:bnfp4nl)*

**Comment by ginccc** [comment]
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/CallbackMatcher.java, line 21 at r3](https://reviewable.io:443/reviews/labsai/eddi/89#-KzPVr38lClJ66p3UNeO:-KzTQvJNOGMe1sWFuG2A:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/3e43e2f40c404fb8dfbf268ca02d195230c17512/backupservice-impl/src/main/java/ai/labs/backupservice/impl/CallbackMatcher.java#L21)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

this should be easy to unit test
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/89)*

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/89#-:-KzTUnAMbrzulq9K5vaM:bnfp4nl)*

**Comment by AlmaasAre** [comment]
:lgtm:

---

Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/89#-:-KzTpvXr84u4b7YuQPZK:bnfp4nl)*

**Pull request merged**
