### PR TITLE
Feature/output templating

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/51)

### CODE REVIEW

**Comment by forjes14** [comment]
Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java, line 78 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-Kqg_37CDYivCyqOC_qF:-Kqg_37Dh3Va9TDoyYDY:bo2iez2) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java#L78)):*
> ```Java
>         if (object != null) {
>             result.put(objectKeyPathQualifier, object.objectKeyPath);
>             result.put(objectValueQualifier, object.objectValue);
> ```

No need for the try/catch?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java, line 78 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-Kqg_37CDYivCyqOC_qF:-Kqgi_FtILTRaFleSH-3:bffv2i7) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java#L78)):*
<details><summary><i>Previously, forjes14 (Jesper M. Førisdahl) wrote…</i></summary><blockquote>

No need for the try/catch?
</blockquote></details>

as said in the chat, jsonSerialization could have thrown an exception, but it was a misconception at the beginning to use it there anyways, so since it is not needed anymore, also no try-catch.. :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 45 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmEKwpkNC3TCvlkL9:-KqgmEKwpkNC3TCvlkLA:b-7syqj7) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L45)):*
> ```Java
> 
>         HashMap<String, Object> dynamicAttributesMap = new HashMap<>();
>         for (IData<Context> contextData : contexts) {
> ```

Map also supports streams. Get rid of `for` cycles please.

---

*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 54 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmgjfC3qj6KEiK-BP:-KqgmgjfC3qj6KEiK-BQ:bl7z9y6) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L54)):*
> ```Java
>         }
> 
>         for (IData<String> output : outputs) {
> ```

Usually, it's a bad practice to mutate the param. If it's unavoidable, use `forEach` function here instead of `for` cycle. As a general rule, you have to have veeery strong motivation for using `for` cycle (as far as any cycle). Try to avoid them as hard as you can. Here million examples how to do so http://winterbe.com/posts/2014/07/31/java8-stream-tutorial-examples/


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by forjes14** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51#-:-Kqgo98rEl3QDppe27PY:bnfp4nl)*

**Comment by ginccc** [comment]
*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 54 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmgjfC3qj6KEiK-BP:-Kqgs-eJLhl2DajNNTEX:bygy69s) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L54)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

Usually, it's a bad practice to mutate the param. If it's unavoidable, use `forEach` function here instead of `for` cycle. As a general rule, you have to have veeery strong motivation for using `for` cycle (as far as any cycle). Try to avoid them as hard as you can. Here million examples how to do so http://winterbe.com/posts/2014/07/31/java8-stream-tutorial-examples/


</blockquote></details>

you do realize that there is no such thing as "forEach" in Java.. In fact, what you see here is a foreach... ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by ginccc** [comment]
*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 45 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmEKwpkNC3TCvlkL9:-KqgsLen2lklWYyavhEq:bwiedr1) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L45)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

Map also supports streams. Get rid of `for` cycles please.
</blockquote></details>

you definitely got a point here, although I am not quite convinced why this is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by ginccc** [comment]
*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 54 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmgjfC3qj6KEiK-BP:-Kqgs_FRM-n7niVgCi3F:b-yr7ryh) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L54)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

you do realize that there is no such thing as "forEach" in Java.. In fact, what you see here is a foreach... ;-)
</blockquote></details>

ah, you mean the method.. sorry, though you mean there is forEach keyword.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 54 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmgjfC3qj6KEiK-BP:-Kqgse5Eci74q8tJTv4d:b-tnat00) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L54)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

ah, you mean the method.. sorry, though you mean there is forEach keyword.. 
</blockquote></details>

Yeah, method, that's right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 45 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmEKwpkNC3TCvlkL9:-KqgskvoXlNSVzGcX0Uu:b-ljd11w) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L45)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

you definitely got a point here, although I am not quite convinced why this is better.
</blockquote></details>

It's a matter of discussion OOP vs FP. But we use FP everywhere in our TypeScript code. So why not to use it here, if even old-school Java allows you to do so.

In this particular case using map function instead of for loop gives you better control of side effects, clearer code, much more clear semantic (hard to make a mistake), less code (means fewer bugs), and finally performance gains in some cases. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by ginccc** [comment]
*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 45 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmEKwpkNC3TCvlkL9:-Kqgxwd_wAgPAf0qnALu:b-7rl0jd) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L45)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

It's a matter of discussion OOP vs FP. But we use FP everywhere in our TypeScript code. So why not to use it here, if even old-school Java allows you to do so.

In this particular case using map function instead of for loop gives you better control of side effects, clearer code, much more clear semantic (hard to make a mistake), less code (means fewer bugs), and finally performance gains in some cases. 
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by ginccc** [comment]
*[templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java, line 54 at r2](https://reviewable.io:443/reviews/labsai/eddi/51#-KqgmgjfC3qj6KEiK-BP:-KqgxywbiCeW_b6JYoIL:b-7rl0jd) ([raw file](https://github.com/labsai/eddi/blob/a93bb85d197414fac2dd6ba6cec4d3c8ab755f40/templateengine-impl-thymeleaf/src/main/java/ai/labs/templateengine/OutputTemplateTask.java#L54)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

Yeah, method, that's right
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51)*

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: 16 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/51#-:-Kqgz5g9VVzTxBwcDa0h:bnfp4nl)*

**Pull request merged**
