### PR TITLE
Improvement/parser

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/71)

### CODE REVIEW

**Comment by forjes14** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71#-:-KsEJyXStaC451i4QkQU:bnfp4nl)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[semanticparser-impl/src/main/java/ai/labs/parser/correction/DamerauLevenshteinCorrection.java, line 64 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsEO0S6Bw-QgUYystoU:-KsEO0S6Bw-QgUYystoV:b3p64p6) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/DamerauLevenshteinCorrection.java#L64)):*
> ```Java
>             double matchingAccuracy = 1.0 - foundWord.distance;
>             ret.add(new FoundWord(foundWord.word, true, matchingAccuracy));
>         });
> ```

```
return foundWords.map(foundWord -> {
   double matchingAccuracy = 1.0 - foundWord.distance;
   return new FoundWord(foundWord.word, true, matchingAccuracy);
})
```

---

*[semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java, line 35 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsERIy--tR4qEK4JAEA:-KsERIy--tR4qEK4JAEB:b-ul8qop) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java#L35)):*
> ```Java
>         if (!word.isEmpty()) {
>             possibleTerms.clear();
>             for (int i = 0; i < word.length(); i++) {
> ```

I've been looking into these two cycles for 15 minutes and I didn't understand what is it about. If it's the known algorithm, please leave the comment with its name. If it's your own algorithm, leave some descriptions. But better of all, fully rewrite this part of the code. Here reasons why:

1) For++ cycle. They are almost always places for mistakes
2) Descending counter. Why? Do you really need it?
3) Change the counter inside the cycle's body is a very bad practice. Please avoid it at all costs.

Usually any super-custom cycle logic can be replaced with reduce function.

---

*[semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java, line 58 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsET4bMqIH_Kp6jimKY:-KsET4bMqIH_Kp6jimKZ:bt27gmx) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java#L58)):*
> ```Java
>                 map(dictionary -> dictionary.lookupTerm(part)).
>                 filter(result -> result.size() > 0).
>                 findFirst().orElse(IDictionary.NO_WORDS_FOUND);
> ```

Perfect! I like it very much!! 


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71)*

**Comment by ginccc** [comment]
*[semanticparser-impl/src/main/java/ai/labs/parser/correction/DamerauLevenshteinCorrection.java, line 64 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsEO0S6Bw-QgUYystoU:-KsEd6LuuDaym2SXB69r:bhj5cbk) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/DamerauLevenshteinCorrection.java#L64)):*
> return foundWords.map(foundWord -> {
>    double matchingAccuracy = 1.0 - foundWord.distance;
>    return new FoundWord(foundWord.word, true, matchingAccuracy);
> })
good catch! more like this though:
```
return foundWords.stream().map(foundWord -> {
            double matchingAccuracy = 1.0 - foundWord.distance;
            return new FoundWord(foundWord.word, true, matchingAccuracy);
        }).collect(Collectors.toList());
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71)*

**Comment by ginccc** [comment]
*[semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java, line 35 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsERIy--tR4qEK4JAEA:-KsEgLeJzj-dTk19AD32:b-kkq5ua) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java#L35)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

I've been looking into these two cycles for 15 minutes and I didn't understand what is it about. If it's the known algorithm, please leave the comment with its name. If it's your own algorithm, leave some descriptions. But better of all, fully rewrite this part of the code. Here reasons why:

1) For++ cycle. They are almost always places for mistakes
2) Descending counter. Why? Do you really need it?
3) Change the counter inside the cycle's body is a very bad practice. Please avoid it at all costs.

Usually any super-custom cycle logic can be replaced with reduce function.
</blockquote></details>

It is supposed to split up words in a string that has no spaces, such as: hellocanyoupleasetellmewhenthenextcoursewillstart
the problem with that is, that a contains wouldn't work well, since you might end up catching words like "ill" instead of will, so you will have to check the longest words first, and only if the rest of the string is also findable as words, otherwise it is not a match. the reason for reverse is a good question. I remember there was a good reason for it, i will have to try to remember why.. :-D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[semanticparser-impl/src/main/java/ai/labs/parser/correction/DamerauLevenshteinCorrection.java, line 64 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsEO0S6Bw-QgUYystoU:-KsHRDV-nGU2DVY1z_IZ:b-7jzv7t) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/DamerauLevenshteinCorrection.java#L64)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

> return foundWords.map(foundWord -> {
>    double matchingAccuracy = 1.0 - foundWord.distance;
>    return new FoundWord(foundWord.word, true, matchingAccuracy);
> })
good catch! more like this though:
```
return foundWords.stream().map(foundWord -> {
            double matchingAccuracy = 1.0 - foundWord.distance;
            return new FoundWord(foundWord.word, true, matchingAccuracy);
        }).collect(Collectors.toList());
```
</blockquote></details>

right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71)*

**Comment by denistakeda** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java, line 35 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsERIy--tR4qEK4JAEA:-KsHbm3UyOBNgv3smLYT:b-6rguj3) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java#L35)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

It is supposed to split up words in a string that has no spaces, such as: hellocanyoupleasetellmewhenthenextcoursewillstart
the problem with that is, that a contains wouldn't work well, since you might end up catching words like "ill" instead of will, so you will have to check the longest words first, and only if the rest of the string is also findable as words, otherwise it is not a match. the reason for reverse is a good question. I remember there was a good reason for it, i will have to try to remember why.. :-D
</blockquote></details>

I'm not super expert in Java, so here the code on TypeScript. I'm sure you can transform it to Java easily
```
const dictionary: string[] = [
  'hello',
  'can',
  'you',
  'please',
  'tell',
  'me',
  'when',
  'the',
  'next',
  'course',
  'will',
  'start',

  'ill', // <- place for mistake
];

function parseText(text: string): string[] {
  for (let rightBorder = text.length; rightBorder > 0; rightBorder--) {
    for (let leftBorder = 0; leftBorder < rightBorder; leftBorder++) {
      const wordCandidate: string = text.substring(leftBorder, rightBorder);
      if (isWord(wordCandidate)) {
        return parseText(text.substring(0, leftBorder)).concat(wordCandidate);
      }
    }
  }
  return [];
}

function isWord(wordCandidate: string): boolean {
  return _.includes(dictionary, wordCandidate);
}

console.log(parseText('hellocanyoupleasetellmewhenthenextcoursewillstart')); // ->  ["hello", "can", "you", "please", "tell", "me", "when", "the", "next", "course", "will", "start"]
```
It's still not perfect and can be improved much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71)*

**Comment by ginccc** [comment]
*[semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java, line 35 at r2](https://reviewable.io:443/reviews/labsai/eddi/71#-KsERIy--tR4qEK4JAEA:-KsN_uJTqcSgcpoEtrh5:b-n0fgi6) ([raw file](https://github.com/labsai/eddi/blob/51097a0af5b91b712198c624e418833ca4f36f9f/semanticparser-impl/src/main/java/ai/labs/parser/correction/MergedTermsCorrection.java#L35)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

I'm not super expert in Java, so here the code on TypeScript. I'm sure you can transform it to Java easily
```
const dictionary: string[] = [
  'hello',
  'can',
  'you',
  'please',
  'tell',
  'me',
  'when',
  'the',
  'next',
  'course',
  'will',
  'start',

  'ill', // <- place for mistake
];

function parseText(text: string): string[] {
  for (let rightBorder = text.length; rightBorder > 0; rightBorder--) {
    for (let leftBorder = 0; leftBorder < rightBorder; leftBorder++) {
      const wordCandidate: string = text.substring(leftBorder, rightBorder);
      if (isWord(wordCandidate)) {
        return parseText(text.substring(0, leftBorder)).concat(wordCandidate);
      }
    }
  }
  return [];
}

function isWord(wordCandidate: string): boolean {
  return _.includes(dictionary, wordCandidate);
}

console.log(parseText('hellocanyoupleasetellmewhenthenextcoursewillstart')); // ->  ["hello", "can", "you", "please", "tell", "me", "when", "the", "next", "course", "will", "start"]
```
It's still not perfect and can be improved much.
</blockquote></details>

this looks quite good, I need to check if it misses anything, but apart from that, nice job!! Nonetheless, it is really changing semantics here, so nothing for this pullrequest, I will pull over your suggestions into another branch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71)*

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: 27 of 28 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/71#-:-KsNiQRjezXmHXhhKqzw:bnfp4nl)*

**Pull request merged**
