### PR TITLE
Improvement/added context handover to chat ui

### PR DESCRIPTION
**Pull request by ginccc**
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/63)

### CODE REVIEW

**Comment by forjes14** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/63#-:-KrZsvwEswkh1tMcvafc:bnfp4nl)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[apiserver/resources/html/chat.html, line 11 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_488z4DV6qHVgkkxK:-Kr_488z4DV6qHVgkkxL:b7mm2u9) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/resources/html/chat.html#L11)):*
> ```HTML
> <body>
> 
> <div style="position: absolute">
> ```

add a class to the div and move the style into a stylesheet

---

*[apiserver/src/main/resources/js/chat.js, line 119 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_4_le0iez-TDjPDSU:-Kr_4_le0iez-TDjPDSV:b-pktvmo) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L119)):*
> ```JavaScript
> 
>         $.ajax({
>             type: 'POST',
> ```

would create a helper for this 

`const promise = network.post(url, data);`

the helper should set contentType, stringify the requestBody and use constants for "POST" etc

---

*[apiserver/src/main/resources/js/chat.js, line 120 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_4QOVAOZucGxe54Z2:-Kr_4QOVAOZucGxe54Z3:b-kstinm) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L120)):*
> ```JavaScript
>         $.ajax({
>             type: 'POST',
>             url: '/bots/' + eddi.environment + '/' + eddi.botId + '/' + eddi.conversationId,
> ```

this should have a factory instead.

`routing.bots(botId, conversationId)`

---

*[apiserver/src/main/resources/js/chat.js, line 131 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_513HuyNTf4lIMIK_:-Kr_513HuyNTf4lIMIKa:b-7lhtug) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L131)):*
> ```JavaScript
> 
>     const loadConversationLog = function () {
>         $.get('/bots/' + eddi.environment + '/' + eddi.botId + '/' + eddi.conversationId).done(
> ```

use suggestion from earlier

---

*[apiserver/src/main/resources/js/chat.js, line 200 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_5K_1qjqN1nutrQIx:-Kr_5K_1qjqN1nutrQIy:b3kw9) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L200)):*
> ```JavaScript
> 
>     const deployBot = function (environment, botId, botVersion) {
>         $.post('/administration/' + environment + '/deploy/' + botId + '?version=' + botVersion).done(function () {
> ```

î

---

*[apiserver/src/main/resources/js/chat.js, line 206 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_5It_c6ZIus6f3Ggs:-Kr_5It_c6ZIus6f3Ggt:b3kw9) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L206)):*
> ```JavaScript
> 
>     const checkBotDeploymentStatus = function () {
>         $.get('/administration/' + eddi.environment + '/deploymentstatus/' + eddi.botId + '?version=' + eddi.botVersion).done(function (data) {
> ```

î

---

*[apiserver/src/main/resources/js/chat.js, line 218 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_5MbNeZxZFfwQEYEM:-Kr_5MbNeZxZFfwQEYEN:b3kw9) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L218)):*
> ```JavaScript
> 
>     const createConversation = function (environment, botId) {
>         $.post('/bots/' + environment + '/' + botId).done(function (data, status, xhr) {
> ```

î

---

*[apiserver/src/main/resources/js/chat.js, line 226 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_5NChqtnijECnTSr6:-Kr_5NChqtnijECnTSr7:b3kw9) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L226)):*
> ```JavaScript
> 
>     const checkConversationStatus = function (environment, botId, conversationId) {
>         $.get('/bots/' + environment + '/' + botId + '/' + conversationId).always(function (data, status) {
> ```

î

---

*[apiserver/src/main/resources/js/chat.js, line 271 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_5RAJYt-UjESUEtTD:-Kr_5RAJYt-UjESUEtTE:b3kw9) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L271)):*
> ```JavaScript
>     const checkBotDeployment = function () {
>         //check if bot is deployed
>         $.get('/administration/' + eddi.environment + '/deploymentstatus/' + eddi.botId + '?version=' + eddi.botVersion)
> ```

î

---

*[apiserver/src/main/resources/js/chat.js, line 315 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_5S0xi4zzehiAgsy5:-Kr_5S0xi4zzehiAgsy6:b3kw9) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L315)):*
> ```JavaScript
>             checkBotDeployment();
>         } else {
>             $.get('/botstore/bots/' + eddi.botId + '/currentversion', function (data) {
> ```

î

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/63)*

**Comment by kennethlynne** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/63)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[apiserver/src/main/resources/js/chat.js, line 52 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_6V0w8inkbanjtf_P:-Kr_6V0w8inkbanjtf_Q:bljx8ht) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L52)):*
> ```JavaScript
> 
>     function getMessageText() {
>         const $message_input = $('.message_input');
> ```

many references to DOM elements can be set in constants once instead.

`const messageInput = $('.message_input');`

and reuse it instead of looking up the element multiple times (performance) and avoid issues with missing nodes if the DOM hierarchy changes so the selector does not match (class names change, order change etc, more than one element might have the class etc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/63)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[apiserver/src/main/resources/js/chat.js, line 83 at r2](https://reviewable.io:443/reviews/labsai/eddi/63#-Kr_74pxPZaid3OwCV2C:-Kr_74pxPZaid3OwCV2D:b-u89rj1) ([raw file](https://github.com/labsai/eddi/blob/9bfb18e856a93e5d047754bb7f39a42a6d9298fb/apiserver/src/main/resources/js/chat.js#L83)):*
> ```JavaScript
>     }
> 
>     $('.send_message').click(function () {
> ```

create a reference to these elements in a a constant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/63)*

**Pull request merged**
