### PR TITLE
Feature/input context data to eddi

### PR DESCRIPTION
**Pull request by ginccc**
* added possibility to submit context info along side user input
* added contextmatcher to check for context within rules
** either as string, expressions or even as json object with XPath functionality (http://static.javadoc.io/io.rest-assured/json-path/3.0.2/io/restassured/path/json/JsonPath.html)

integration test for context: https://github.com/labsai/EDDI-integration-tests/blob/master/src/test/java/ai/labs/testing/integration/RestBotEngineTest.java#L311

---
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/48)

### CODE REVIEW

**Comment by denistakeda** [comment]
Review status: 0 of 45 files reviewed at latest revision, 5 unresolved discussions.

---

*[behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java, line 38 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq66Q9JrrPE4NdeZ9OL:-Kq66Q9JrrPE4NdeZ9OM:b-cc3k89) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java#L38)):*
> ```Java
> 
>             BehaviorConfiguration behaviorJson = objectMapper.readerFor(BehaviorConfiguration.class).readValue(json);
>             for (BehaviorGroupConfiguration groupConfiguration : behaviorJson.getBehaviorGroups()) {
> ```

1) You have a collection as input
2) You wanna get another collection as output
3) The size of input collection is equal to the size of output collection
4) Every item of output collection gets by transformation of item of input collection

If all these are true you have to use `map` function. Please do not iterate over the collection with for loop.
Here the Oracle tutorial for collections: https://docs.oracle.com/javase/tutorial/collections/interfaces/collection.html
you may need lambda expressions: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html

---

*[behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java, line 43 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq68F31rmrXshWyM_sD:-Kq68F31rmrXshWyM_sE:b8im1iy) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java#L43)):*
> ```Java
>                 behaviorSet.getBehaviorGroups().add(behaviorGroup);
> 
>                 for (BehaviorRuleConfiguration behaviorRuleJson : groupConfiguration.getBehaviorRules()) {
> ```

Use map function

---

*[behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java, line 60 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq68Jc4RwIW3J2mnG8R:-Kq68Jc4RwIW3J2mnG8S:b8im1iy) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java#L60)):*
> ```Java
>                                              BehaviorSet behaviorSet) throws CloneNotSupportedException {
>         List<IBehaviorExtension> ret = new LinkedList<>();
>         for (BehaviorRuleElementConfiguration child : children) {
> ```

Use map function

---

*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java, line 38 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq6B-VkGf1fvXplAF8p:-Kq6B-VkGf1fvXplAF8q:bxq5ud5) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java#L38)):*
> ```Java
>     private ExecutionState state = ExecutionState.NOT_EXECUTED;
>     private final String contextKeyQualifier = "contextKey";
>     private final String contextTypeQualifier = "contextType"; // string or expressions
> ```

// string or expressions
This comment doesn't make sense for String variable

---

*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/IBehaviorExtension.java, line 15 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq6Bs_40WNrBxfth1Di:-Kq6Bs_40WNrBxfth1Dj:b-qsyuya) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/IBehaviorExtension.java#L15)):*
> ```Java
>  */
> public interface IBehaviorExtension extends Cloneable {
>     String EXTENSION_PREFIX = "ai.labs.behavior.extension.";
> ```

final?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by forjes14** [comment]
Reviewed 59 of 59 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java, line 11 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq75dQPVad1RRzQpl4E:-Kq75dQQXDcMv692E-zm:bsml3m) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java#L11)):*
> ```Java
> import ai.labs.runtime.client.bots.IBotStoreClientLibrary;
> import ai.labs.runtime.service.ServiceException;
> import lombok.*;
> ```

We should just import the dependencies we need, not whole packages. (Not sure about this, but i think it's more performant)

---

*[runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java, line 14 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq75kOlVImWQuECWwHs:-Kq75kOlVImWQuECWwHt:b2nreh6) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java#L14)):*
> ```Java
> 
> import javax.inject.Inject;
> import java.util.*;
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java, line 38 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq66Q9JrrPE4NdeZ9OL:-Kq7BEaOZKF2ucAne2KG:b-eadytj) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java#L38)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

1) You have a collection as input
2) You wanna get another collection as output
3) The size of input collection is equal to the size of output collection
4) Every item of output collection gets by transformation of item of input collection

If all these are true you have to use `map` function. Please do not iterate over the collection with for loop.
Here the Oracle tutorial for collections: https://docs.oracle.com/javase/tutorial/collections/interfaces/collection.html
you may need lambda expressions: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html
</blockquote></details>

yes, you are correct. I have already used them at other places that have been newly written, but these pieces are from a time were it didn't existed yet and/or I haven't had the knowledge yet how to use them! :-)
Will change this!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java, line 38 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq6B-VkGf1fvXplAF8p:-Kq7Bdf3-0uSP53k4i-C:bscidyt) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java#L38)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

// string or expressions
This comment doesn't make sense for String variable
</blockquote></details>

well, the contextType is the key in the config file defining what type of value to expect, so that the engine can use it properly. it can be either a string, a bunch of expressions or an json object (since last commit)...
so yeah, not really the write place to put this information there about what type of values are possible..
maybe an enum as value...?! mmhhh not sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/IBehaviorExtension.java, line 15 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq6Bs_40WNrBxfth1Di:-Kq7C8W-OTME14ZBEJbb:b-wumx1q) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/IBehaviorExtension.java#L15)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

final?
</blockquote></details>

all properties in interfaces are public, static and final by default. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by ginccc** [comment]
*[runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java, line 11 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq75dQPVad1RRzQpl4E:-Kq7CIqd1SMotYGYWGYk:b-fijk9y) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java#L11)):*
<details><summary><i>Previously, forjes14 (Jesper M. Førisdahl) wrote…</i></summary><blockquote>

We should just import the dependencies we need, not whole packages. (Not sure about this, but i think it's more performant)
</blockquote></details>

it used to be more performant up thill java 5. after that they have rewritten the import in a way that the compiler makes it very effective, one way or the other. So this doesn't matter anymore.
generally, intellij handles the imports automatically, I don't do this manually at all.
I believe it makes it explicit up to a certain number of imports and after that just generalize the whole package in order to prevent to many import statements 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by forjes14** [comment]
:lgtm: Just fix what Dennis wrote.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48#-:-Kq7GeUEc36tgZbqhVLc:b-9r2xe6)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java, line 38 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq66Q9JrrPE4NdeZ9OL:-Kq7R9mQl9AAaxNt7ljQ:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java#L38)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

yes, you are correct. I have already used them at other places that have been newly written, but these pieces are from a time were it didn't existed yet and/or I haven't had the knowledge yet how to use them! :-)
Will change this!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java, line 43 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq68F31rmrXshWyM_sD:-Kq7RBiOfrG8GT6pQ9OH:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java#L43)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

Use map function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java, line 60 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq68Jc4RwIW3J2mnG8R:-Kq7RDsUQVgJe3j0_Lr-:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/BehaviorDeserialization.java#L60)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

Use map function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by denistakeda** [comment]
Review status: 44 of 45 files reviewed at latest revision, 2 unresolved discussions.

---

*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java, line 38 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq6B-VkGf1fvXplAF8p:-Kq7S3uMEPCzJm3KXCXy:bizpl3f) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java#L38)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

well, the contextType is the key in the config file defining what type of value to expect, so that the engine can use it properly. it can be either a string, a bunch of expressions or an json object (since last commit)...
so yeah, not really the write place to put this information there about what type of values are possible..
maybe an enum as value...?! mmhhh not sure
</blockquote></details>

Enum is a standard way to represent this type of information

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: 44 of 45 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48#-:-Kq83QzMWw_OUE7o3b-L:bnfp4nl)*

**Comment by ginccc** [comment]
*[behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java, line 38 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq6B-VkGf1fvXplAF8p:-Kq8A4FSCJjm2oKTnHKH:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/behavior-impl/src/main/java/ai/labs/behavior/impl/extensions/ContextMatcher.java#L38)):*
<details><summary><i>Previously, denistakeda (Denis Krivosheev) wrote…</i></summary><blockquote>

Enum is a standard way to represent this type of information
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Comment by ginccc** [comment]
*[runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java, line 14 at r1](https://reviewable.io:443/reviews/labsai/eddi/48#-Kq75kOlVImWQuECWwHs:-Kq8B5SiTbzwbh3tqvMd:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/c5122a105650a024584a1fb86993011d40cca710/runtime-impl/src/main/java/ai/labs/runtime/internal/BotFactory.java#L14)):*
<details><summary><i>Previously, forjes14 (Jesper M. Førisdahl) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/48)*

**Pull request merged**
