### PR TITLE
Git import export

### PR DESCRIPTION
**Pull request by rolandpickl**
This is the beta implemenation of the GIT Backup integration. Currently the integration is fully manual, so one creates a git repository and then one can push the changes in EDDI to that repo. The feature can be used, but there are still open issues with pull/import and the automatic update to git is currently not implemented. This will be part of the next version

---
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/135)

### CODE REVIEW

**Comment by ginccc** [comment]
___
*[backupservice-defintion/src/main/java/ai/labs/backupservice/IGitBackupService.java, line 14 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft2AQuEpI_46AvM_t1:-Lft2AQv6Nvk-1rWCF9j:b-34mgo8) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/backupservice-defintion/src/main/java/ai/labs/backupservice/IGitBackupService.java#L14)):*
> ```Java
> @Api(value = "Backup")
> @Path("/backup/git")
> public interface IGitBackupService {
> ```

IRestGitBackupService , as classes containing ..Rest.. in EDDI indicating that this class is a jax-rs restful resource.

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java, line 83 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft2Tfa2WWJajIVrZsB:-Lft2Tfa2WWJajIVrZsC:b-chypbm) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java#L83)):*
> ```Java
>             StringWriter sw = new StringWriter();
>             PrintWriter pw = new PrintWriter(sw);
>             e.printStackTrace(pw);
> ```

better: log.error(e.getLocalizedMessage(), e);

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java, line 114 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft30AXEbAH6S0D_8Gc:-Lft30AY-PY8t9sYquWj:bu1l40d) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java#L114)):*
> ```Java
>             StringWriter sw = new StringWriter();
>             PrintWriter pw = new PrintWriter(sw);
>             e.printStackTrace(pw);
> ```

use slf4j like mentioned above

this block repeats itself, pls extract to a method

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java, line 140 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft3J0v9_knB8ORRrTI:-Lft3J0v9_knB8ORRrTJ:b-fh7jlo) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java#L140)):*
> ```Java
>                         .commit()
>                         .setMessage(commitMessage)
>                         .setCommitter("EDDI", "eddi@labs.ai")
> ```

dynamic property?

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java, line 185 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft3kEF0ZHzcgi1nE6D:-Lft3kEF0ZHzcgi1nE6E:b6p1lrc) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java#L185)):*
> ```Java
>             PrintWriter pw = new PrintWriter(sw);
>             e.printStackTrace(pw);
>             return Response.status(Response.Status.NOT_FOUND).entity("commit " + e.getMessage() + " exception " + sw.toString()).build();
> ```

log.debug(e.getLocalizedMessage(), e);
throw new NotFoundException(e.getLocalizedMessage(), e);

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java, line 190 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft3v9-EXwB-s9MLecQ:-Lft3v9-EXwB-s9MLecR:b-h6lvq0) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitBackupService.java#L190)):*
> ```Java
>             PrintWriter pw = new PrintWriter(sw);
>             e.printStackTrace(pw);
>             return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity("commit " + e.getMessage() + " exception " + sw.toString()).build();
> ```

can be also like this: 
log.error(e.getLocalizedMessage(), e);
throw new InternalServerErrorException(e.getLocalizedMessage(), e);

Is there an advantage in using the PrintWriter?

**Comment by ginccc** [comment]
___
*[backupservice-impl/pom.xml, line 44 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft4_4f6Tk84DSof9w-:-Lft4_4f6Tk84DSof9w0:b-25gbll) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/backupservice-impl/pom.xml#L44)):*
> ```XML
>             <groupId>org.eclipse.jgit</groupId>
>             <artifactId>org.eclipse.jgit</artifactId>
>             <version>5.3.0.201903130848-r</version>
> ```

In April a new version came out: 5.3.1.201904271842-r
Does it work with this one as well?

**Comment by ginccc** [comment]
___
*[semanticparser-impl/src/main/java/ai/labs/parser/extensions/dictionaries/TimeExpressionDictionary.java, line 9 at r2](https://reviewable.io/reviews/labsai/eddi/135#-Lft6G1oE0XUR-XsxLUo:-Lft6G1p3fIJtiG58AKR:b-axav58) ([raw file](https://github.com/labsai/eddi/blob/13ea9d28c3629e4c72d9848425e2cb3777e61ee0/semanticparser-impl/src/main/java/ai/labs/parser/extensions/dictionaries/TimeExpressionDictionary.java#L9)):*
> ```Java
> import ai.labs.utilities.LanguageUtilities;
> 
> import java.util.ArrayList;
> ```

ArrayList is not in use in this class?!

**Comment by rolandpickl** [comment]
The print writer stuff was just for debugging, so I could get the stack of the exception easier. It is removed

**Comment by ginccc** [comment]
:lgtm:

**Pull request merged**
