### PR TITLE
Facebook integration

### PR DESCRIPTION
**Pull request by rolandpickl**
rebased facebook integration to current branch. Undid all review issues in other code. Please review.

eddi is working with facebook, as seen here:
https://www.facebook.com/Med-Bot-763360187180348/

Bot understands: hi, how are you and bye

---
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/75)

### CODE REVIEW

**Comment by ginccc** [comment]
*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 209 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-KsbguGY-ATTIcnXINKM:-KsbguGZmFpFFgi0OKmL:be7yv33) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L209)):*
> ```Java
>             for (JsonNode conversationStep : conversationStepsArray) {
>                 for (JsonNode conversationStepValues : conversationStep.get("conversationStep")) {
>                     if (conversationStepValues.get("key") != null && conversationStepValues.get("key").asText().startsWith("output:text")) {
> ```

There could be many "output:text" items. e.g.: 
output:text:welcome1
output:text:welcome2
output:text:greeting
output:text:question
...

each output should end up in a separate "chatbubble" on the client. So rather make a List of output text and send each separately... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/75)*

**Comment by ginccc** [comment]
*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 59 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-KsbheuVDrZAECAavtqZ:-KsbheuW8fYb0eCGZGHr:bb6m8jq) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L59)):*
> ```Java
> public class FacebookEndpoint implements IFacebookEndpoint {
>     private static final String RESOURCE_URI_CHANNELCONNECTOR = "eddi://ai.labs.channel.facebook";
>     private static final String AI_LABS_USER_AGENT = "Jetty 9.3/HTTP CLIENT - AI.LABS.EDDI";
> ```

9.4 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/75)*

**Comment by ginccc** [comment]
*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 159 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-KsbhmJ4oQSTsSystFPS:-KsbhmJ4oQSTsSystFPT:bssg3ix) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L159)):*
> ```Java
>                 botId, "/",
>                 conversationId,
>                 "?returnDetails=true");
> ```

are you sure you need the returnDetails to be true? I don't see you using it anywhere.. input, output, action, and quickreply is public by default and will be included anyways

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/75)*

**Comment by ginccc** [comment]
*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 180 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-Ksbi9CdM3SDiwqNm6uR:-Ksbi9CdM3SDiwqNm6uS:b-bxzuqz) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L180)):*
> ```Java
>                 messengerClientCache.get(botId).getSendClient().sendSenderAction(senderId, SenderAction.TYPING_OFF);
>             } catch (MessengerApiException | MessengerIOException e) {
>                 log.error(e.getMessage(), e);
> ```

e.getLocalizedMessage()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/75)*

**Comment by rolandpickl** [comment]
review comments implemented

**Comment by rolandpickl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 59 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-KsbheuVDrZAECAavtqZ:-KseHzE3Oo9YHhV6M021:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L59)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

9.4 
</blockquote></details>

Done.

---

*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 159 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-KsbhmJ4oQSTsSystFPS:-KseI-edQHpc8h5XdRJm:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L159)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

are you sure you need the returnDetails to be true? I don't see you using it anywhere.. input, output, action, and quickreply is public by default and will be included anyways
</blockquote></details>

Done.

---

*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 180 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-Ksbi9CdM3SDiwqNm6uR:-KseHyUn8sB2uvR_u5jF:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L180)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

e.getLocalizedMessage()
</blockquote></details>

Done.

---

*[facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java, line 209 at r1](https://reviewable.io:443/reviews/labsai/eddi/75#-KsbguGY-ATTIcnXINKM:-KseHxC3N7XXoNq1oAaS:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/e1f481d9d065bae504df6c77c8889c81cd4a6af5/facebookmessenger-impl/src/main/java/ai/labs/facebookmessenger/endpoint/FacebookEndpoint.java#L209)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

There could be many "output:text" items. e.g.: 
output:text:welcome1
output:text:welcome2
output:text:greeting
output:text:question
...

each output should end up in a separate "chatbubble" on the client. So rather make a List of output text and send each separately... 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/75)*

**Pull request merged**
