### PR TITLE
Feature/output new format

### PR DESCRIPTION
**Pull request by ginccc**
This feature is covering the new OutputConfiguration format such as the following json file..
also, templating has been improved to also support templating of quickReply messages now
```
{
  "outputSet": [
    {
      "action": "welcome",
      "occurred": 0,
      "outputs": [
        {
          "type": "text",
          "valueAlternatives": [
            "Hi {name}! I'm Differ Bot and I am Here to help you get stuff done in your courses. We know it can be a bit weird to start a new class with new people. I am putting together small groups of likeminded people who are in the same boat. Would you like to join? You can leave at anytime."
          ]
        },
        {
          "type": "image",
          "valueAlternatives": [
            "something.gif"
          ]
        },
        {
          "type": "audio",
          "valueAlternatives": [
            "someAudio.mp3"
          ]
        }
      ],
      "quickReplies": [
        {
          "value": "Cool, let’s do it",
          "expressions": "confirmation(continue_create_peer_group)"
        },
        {
          "value": "No thanks!",
          "expressions": "confirmation(cancel_create_peer_group)"
        }
      ]
    },
    {
      "action": "show_how_differ_works",
      "output": [
        "Would you like to know a little bit about how Differ works?"
      ],
      "quickReplies": [
        {
          "value": "Yes, give me the highlights!",
          "expressions": "confirmation(give_differ_highlights)"
        },
        {
          "value": "No thanks!",
          "expressions": "confirmation(no_differ_highlights)"
        }
      ],
      "occurrence": 0
    },
    {
      "action": "how_differ_works",
      "output": [
        {
          "type": "text",
          "valueAlternatives": [
            "{img of Home} It’s quite simple really. Stay up to date with your classmates and teachers can be stressful, so we put all your important messages on home ( direct messages, group chats and announcements from you community)"
          ]
        }
      ],
      "quickReplies": [
        {
          "value": "Continue",
          "expressions": "confirmation(give_differ_highlights)"
        },
        {
          "value": "Stop this madness",
          "expressions": "confirmation(no_differ_highlights)"
        }
      ],
      "occurred": 0
    },
    {
      "action": "how_differ_works",
      "output": [
        {
          "type": "image",
          "valueAlternatives": [
            "img_of_communities.png"
          ]
        },
        {
          "type": "text",
          "valueAlternatives": [
            "Communities are where you can reach all the people taking the same classes or courses as you, get answers, or maybe discuss what’s happening next weekend"
          ]
        }
      ],
      "quickReplies": [
        {
          "value": "Continue",
          "expressions": "confirmation(give_differ_highlights)"
        },
        {
          "value": "Stop this madness",
          "expressions": "confirmation(no_differ_highlights)"
        }
      ],
      "occurred": 1
    },
    {
      "action": "how_differ_works",
      "output": [
        {
          "type": "image",
          "valueAlternatives": [
            "img_of_bookmarks.png"
          ]
        },
        {
          "type": "text",
          "valueAlternatives": [
            "Bookmarks is where you can find all the files and links shared in your communities, so you don’t have to worry about finding what you need"
          ]
        }
      ],
      "quickReplies": [
        {
          "value": "Continue",
          "expressions": "continue(knowing_about_desktop_app)"
        }
      ],
      "occurred": 2
    },
    {
      "action": "knowing_about_desktop_app",
      "output": [
        {
          "type": "text",
          "valueAlternatives": "By the way, did you know differ has a desktop app as well? it makes it easier to stay connected when you are working on you computer."
        }
      ],
      "quickReplies": [
        {
          "value": "Continue",
          "expressions": "continue(knowing_about_desktop_app)"
        }
      ],
      "occurred": 0
    },
    {
      "action": "knowing_about_desktop_app",
      "output": [
        {
          "type": "text",
          "valueAlternatives": "You can go to differ.chat/download to get the desktop app. Thanks you for reading all my babble. I will pop by from time to time try to help out, like to tell you when your course plan is ready. But i will leave you be for now :-)  Have a blast at fadderullan. see you later"
        },
        {
          "type": "image",
          "valueAlternatives": [
            "some_gif.gif"
          ]
        }
      ],
      "occurred": 1
    }
  ]
}
```

This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/56)

### CODE REVIEW

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: 0 of 30 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56#-:-KrA9kMxt8po8ywbyAxR:bnfp4nl)*

**Comment by forjes14** [comment]
:lgtm:

---

Reviewed 32 of 32 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[configurationrepository-definition/src/main/java/ai/labs/resources/rest/output/model/OutputConfiguration.java, line 34 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrA9PSXzxgzv003ypIW:-KrA9PSXzxgzv003ypIX:bjd8opt) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/configurationrepository-definition/src/main/java/ai/labs/resources/rest/output/model/OutputConfiguration.java#L34)):*
> ```Java
>     public int hashCode() {
>         int result = action.hashCode();
>         result = 31 * result + occurred;
> ```

What does the number 31 represent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56#-:-KrACIDq_6OuBVuRPxDZ:bnfp4nl)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[configurationrepository-definition/src/main/java/ai/labs/resources/rest/output/model/OutputConfiguration.java, line 34 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrA9PSXzxgzv003ypIW:-KrAGLkRwcdT4Nf-fUm9:b-r2gikw) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/configurationrepository-definition/src/main/java/ai/labs/resources/rest/output/model/OutputConfiguration.java#L34)):*
<details><summary><i>Previously, forjes14 (Jesper M. Førisdahl) wrote…</i></summary><blockquote>

What does the number 31 represent?
</blockquote></details>

dafuq je. Please add a named constant for it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 136 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHPmOu-keoQ8huTgQ:-KrAHPmOu-keoQ8huTgR:b7lv2v7) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L136)):*
> ```Java
>     }
> 
>     private int countActionOccurrence(IConversationMemory.IConversationStepStack conversationStepStack,
> ```

Occurrences 

---

*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 153 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHX5ipU9xpRRh5nds:-KrAHX5ipU9xpRRh5ndt:b-36exzb) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L153)):*
> ```Java
>     }
> 
>     private List<OutputValue> convertOutputTypesConfig(List<OutputConfiguration.OutputType> configOutputs) {
> ```

I think name could be improved to be more explainatory. Convert from what to what?

---

*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 162 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHeN53cINXtZgx6-V:-KrAHeN53cINXtZgx6-W:b-36exzb) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L162)):*
> ```Java
>     }
> 
>     private List<QuickReply> convertQuickRepliesConfig(List<OutputConfiguration.QuickReply> configQuickReplies) {
> ```

I think name could be improved to be more explainatory. Convert from what to what?

---

*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 171 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHgdzBs1FlwFUdIik:-KrAHgdzBs1FlwFUdIil:b-36exzb) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L171)):*
> ```Java
>     }
> 
>     private List<QuickReply> convertQuickReplies(List<QuickReply> outputQuickReplies) {
> ```

I think name could be improved to be more explainatory. Convert from what to what?

---

*[outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTaskTest.java, line 61 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAI3aTiOUGMr_3EF63:-KrAI3aTiOUGMr_3EF64:btoj7dc) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTaskTest.java#L61)):*
> ```Java
>         when(conversationStepStack.get(anyInt())).then(invocation -> conversationStep);
>         when(conversationStep.getLatestData(eq("action"))).then(invocation ->
>                 new Data<>("action2", Arrays.asList("someAction2", "someOtherAction2")));
> ```

make named constants out of "action1", "action2", "someAction2" etc. Could cause some headaches if subtle typos where introduced

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java, line 116 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAIQ4m4DKVNaJgS430:-KrAIQ4nKElJJl_Hc9AF:b-n4mcv2) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java#L116)):*
> ```Java
> 
>         outputEntries.add(new OutputEntry("action3", 4, outputValues, quickReply));
>         outputEntries.add(new OutputEntry("action3", 2, outputValues, quickReply));
> ```

named constants for actions etc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[templateengine-impl-thymeleaf/src/test/java/ai/labs/templateengine/OutputTemplateTaskTest.java, line 121 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAJ0r7BgMJ6Lx4sC5-:-KrAJ0r7BgMJ6Lx4sC50:bq39ucy) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/templateengine-impl-thymeleaf/src/test/java/ai/labs/templateengine/OutputTemplateTaskTest.java#L121)):*
> ```Java
>     private void verifyTask(List<QuickReply> expectedPostQuickReplies) {
>         verify(currentStep).getAllData("output");
>         verify(currentStep).getAllData("quickReplies");
> ```

static string constants for "output" and "quickReplies" maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by kennethlynne** [comment]
Reviewed 32 of 32 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java, line 116 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAIQ4m4DKVNaJgS430:-KrAQI0iC0usqWpRPaMm:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java#L116)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

named constants for actions etc?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[templateengine-impl-thymeleaf/src/test/java/ai/labs/templateengine/OutputTemplateTaskTest.java, line 121 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAJ0r7BgMJ6Lx4sC5-:-KrAQKQPwnufaf00oc5D:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/templateengine-impl-thymeleaf/src/test/java/ai/labs/templateengine/OutputTemplateTaskTest.java#L121)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

static string constants for "output" and "quickReplies" maybe?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[configurationrepository-definition/src/main/java/ai/labs/resources/rest/output/model/OutputConfiguration.java, line 34 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrA9PSXzxgzv003ypIW:-KrAQN6amoJn018ExnYN:b-88lo9b) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/configurationrepository-definition/src/main/java/ai/labs/resources/rest/output/model/OutputConfiguration.java#L34)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

dafuq je. Please add a named constant for it
</blockquote></details>

this is generated code and is very typical in java as it is every the same. so in this case i prefer leaving it like this as it would confuse other java developers if this is made differently like usual..   

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 136 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHPmOu-keoQ8huTgQ:-KrAQgyhUK-fMaIlm-br:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L136)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

Occurrences 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 153 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHX5ipU9xpRRh5nds:-KrAQizJ02GzzORyJ89F:b6n7qar) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L153)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I think name could be improved to be more explainatory. Convert from what to what?
</blockquote></details>

it is meant to convert from configuration file values to internal OOP structure, but I added method docu for better understand, good point! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 162 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHeN53cINXtZgx6-V:-KrAQvII6SCGyyjTesq8:b2ss7xm) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L162)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I think name could be improved to be more explainatory. Convert from what to what?
</blockquote></details>

see comment above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java, line 171 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAHgdzBs1FlwFUdIik:-KrAQzFhu04WwCSNzuxL:b-2g9kg3) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/main/java/ai/labs/output/impl/OutputGenerationTask.java#L171)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I think name could be improved to be more explainatory. Convert from what to what?
</blockquote></details>

this method is completely redundant as it converts into the very same format, thus, not needed at all.. thanks for making me take a look at it :-D  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by ginccc** [comment]
*[outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTaskTest.java, line 61 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAI3aTiOUGMr_3EF63:-KrAREg-awQxB-5ZCFaO:b-896fix) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTaskTest.java#L61)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

make named constants out of "action1", "action2", "someAction2" etc. Could cause some headaches if subtle typos where introduced
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java, line 116 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAIQ4m4DKVNaJgS430:-KrASeSHp1CFKoFlDWyd:b73efwa) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java#L116)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not really (at the time of writing this)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56#-:-KrASpWScJwoMFtceyU6:bnfp4nl)*

**Comment by ginccc** [comment]
*[outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java, line 116 at r2](https://reviewable.io:443/reviews/labsai/eddi/56#-KrAIQ4m4DKVNaJgS430:-KrATHSiz01_T2yVM8Mg:b-3vii0v) ([raw file](https://github.com/labsai/eddi/blob/066b81e933e35a5707f4b5c60dddfee826789db8/outputgeneration-impl/src/test/java/ai/labs/output/impl/OutputGenerationTest.java#L116)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

not really (at the time of writing this)
</blockquote></details>

my fault. only edited one of the two unit test files and forgot to look at the second one. now its done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/labsai/eddi/56)*

**Pull request closed without merging**
