### PR TITLE
Git automatic

### PR DESCRIPTION
**Pull request by rolandpickl**
enable git updates to be automatic on all updates and changes of bots

---
This change is [Reviewable](https://reviewable.io/reviews/labsai/eddi/154)

### CODE REVIEW

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitConfigurationUpdateService.java, line 50 at r1](https://reviewable.io/reviews/labsai/eddi/154#-Lvv_vPhAWeHmoFkBjLg:-Lvv_vPhAWeHmoFkBjLh:bnjzpfn) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitConfigurationUpdateService.java#L50)):*
> ```Java
>     private ExecutorService gitSingleThreadedExecutor = Executors.newFixedThreadPool(1);
> 
>     public GitConfigurationUpdateService() {
> ```

lombok @NoArgsConstructor

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/RestGitBackupService.java, line 151 at r1](https://reviewable.io/reviews/labsai/eddi/154#-Lvvb4x68ontEmsnjvng:-Lvvb4x68ontEmsnjvnh:bb7phvt) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/backupservice-impl/src/main/java/ai/labs/backupservice/impl/RestGitBackupService.java#L151)):*
> ```Java
>                 return Response.status(Response.Status.OK).entity(commit.getFullMessage()).build();
>             } else {
>                 return Response.status(Response.Status.BAD_REQUEST).entity("Git repo not initializsed, please call gitInit first").build();
> ```

typo

**Comment by ginccc** [comment]
___
*[apiserver/config/production/git.properties, line 1 at r1](https://reviewable.io/reviews/labsai/eddi/154#-LvvcVEA8sAjqEt48PB_:-LvvcVEA8sAjqEt48PBa:bolch3i) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/apiserver/config/production/git.properties#L1)):*
> ```INI
> git.url=https://github.com/
> ```

these properties, wouldn't they fit better in a json config file which can be easily altered via rest? this way maybe even multiple git location could be used?!

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/bootstrap/BackupServiceModule.java, line 40 at r1](https://reviewable.io/reviews/labsai/eddi/154#-LvvdD9A5rDcUtgyNpZV:-LvvdD9A5rDcUtgyNpZW:b3gqpod) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/backupservice-impl/src/main/java/ai/labs/backupservice/bootstrap/BackupServiceModule.java#L40)):*
> ```Java
>         GitConfigurationUpdateService updateService = new GitConfigurationUpdateService();
>         requestInjection(updateService);
>         bindInterceptor(Matchers.any(), new AbstractMatcher<>() {
> ```

any() notwendig? vl besser: annotatedWith()

**Comment by ginccc** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitConfigurationUpdateService.java, line 50 at r1](https://reviewable.io/reviews/labsai/eddi/154#-LvvdXgm4-FjcEN-nvoy:-LvvdXgm4-FjcEN-nvoz:b-1mwfn0) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitConfigurationUpdateService.java#L50)):*
> ```Java
>     private ExecutorService gitSingleThreadedExecutor = Executors.newFixedThreadPool(1);
> 
>     public GitConfigurationUpdateService() {
> ```

Injects bitte als contructor injects, nicht member.

**Comment by rolandpickl** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/bootstrap/BackupServiceModule.java, line 40 at r1](https://reviewable.io/reviews/labsai/eddi/154#-LvvdD9A5rDcUtgyNpZV:-LvvjLXg7LqyDQB7zT78:b-ppiczw) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/backupservice-impl/src/main/java/ai/labs/backupservice/bootstrap/BackupServiceModule.java#L40)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

any() notwendig? vl besser: annotatedWith()
</blockquote></details>

annotatedWith() geht leider nicht, weil ich dann nicht zugriff auf die Method Class bekomme. Und das brauche ich, weil sonst bekommst beim server start die Warnung, dass der Interceptor evt. mehrfach aufgerufen wird. Deshalb auch die Implementierung des Matchers mit annotation present und isSynthetic.

**Comment by rolandpickl** [comment]
___
*[apiserver/config/production/git.properties, line 1 at r1](https://reviewable.io/reviews/labsai/eddi/154#-LvvcVEA8sAjqEt48PB_:-LvwOJT2E_5QfozGKXGN:b3cvcj8) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/apiserver/config/production/git.properties#L1)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

these properties, wouldn't they fit better in a json config file which can be easily altered via rest? this way maybe even multiple git location could be used?!
</blockquote></details>

I changed that, in order to not having username/password accessable via rest interface, but I think you are right, but we will never return the password. I will change that

**Comment by rolandpickl** [comment]
___
*[backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitConfigurationUpdateService.java, line 50 at r1](https://reviewable.io/reviews/labsai/eddi/154#-Lvv_vPhAWeHmoFkBjLg:-LvyJFe_44e9b3TRsGMN:b-fngg4z) ([raw file](https://github.com/labsai/eddi/blob/be76dba0a35c93d690002caa0a8129d007b8b168/backupservice-impl/src/main/java/ai/labs/backupservice/impl/GitConfigurationUpdateService.java#L50)):*
<details><summary><i>Previously, ginccc (Gregor Jarisch) wrote…</i></summary><blockquote>

lombok @NoArgsConstructor
</blockquote></details>

hat jetzt argumets

**Comment by ginccc** [comment]
:lgtm:

**Comment by ginccc** [comment]
:lgtm:

**Comment by ginccc** [comment]
:lgtm:

**Pull request merged**
